"""Tokens

Revision ID: 3e90cc95e2c2
Revises: dbf79b998f80
Create Date: 2020-08-09 16:06:08.533795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e90cc95e2c2'
down_revision = 'dbf79b998f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalid_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invalid_tokens')
    # ### end Alembic commands ###
